
#! @Chapter Maniplex Properties
#! @Section Automorphism group acting on flags, faces, and chains

#! @Arguments M
#! Returns the automorphism group of <A>M</A> as a
#! permutation group action on the flags of <A>M</A>.
DeclareAttribute("AutomorphismGroupOnFlags", IsManiplex);
#! @BeginExampleSession
#! gap> s0 := (3,7)(4,8)(5,6);;
#! gap> s1 := (2,3)(4,6)(5,7);;
#! gap> s2 := (1,2)(3,6)(4,8)(5,7);;
#! gap> poly := Group([s0,s1,s2]);;
#! gap> p:=ARP(poly);
#! regular 3-polytope
#! gap> AutomorphismGroup(p);
#! Group([ (3,7)(4,8)(5,6), (2,3)(4,6)(5,7), (1,2)(3,6)(4,8)(5,7) ])
#! gap> AutomorphismGroupFpGroup(p);
#! <fp group on the generators [ r0, r1, r2 ]>
#! gap> AutomorphismGroupPermGroup(Cube(3));
#! Group([ (3,4), (2,3)(4,5), (1,2)(5,6) ])
#! gap> AutomorphismGroupOnFlags(Cube(3));
#! <permutation group with 3 generators>
#! gap> GeneratorsOfGroup(last);
#! [ (1,20)(2,13)(3,10)(4,34)(5,35)(6,7)(8,27)(9,28)(11,23)(12,24)(14,44)(15,45)(16,18)(17,19)(21,40)(22,41)(25,37)(26,38)(29,48)(30,32)(31,33)(36,47)(39,46)(42,43), 
#!   (1,11)(2,18)(3,4)(5,26)(6,41)(7,8)(9,33)(10,45)(12,15)(13,31)(14,25)(16,28)(17,27)(19,22)(20,38)(21,32)(23,35)(24,34)(29,39)(30,47)(36,43)(37,48)(40,42)(44,46), 
#!   (1,3)(2,7)(4,25)(5,28)(6,13)(8,32)(9,35)(10,20)(11,14)(12,17)(15,47)(16,40)(18,21)(19,24)(22,48)(23,44)(26,42)(27,30)(29,41)(31,39)(33,46)(34,37)(36,45)(38,43) ]
#! @EndExampleSession
#! @EndGroup

#! @Arguments M, I
#! @Returns IsPermGroup
#! @Description Returns a permutation group, representing the action of
#! AutomorphismGroup(<A>M</A>) on the chains of <A>M</A> of type <A>I</A>.
#! If the automorphism group has a standard set of generators in a standard order, then the output
#! is generated by the action of those generators.
DeclareOperation("AutomorphismGroupOnChains", [IsManiplex, IsCollection]);
#! @BeginExampleSession
#! gap> AutomorphismGroupOnChains(HemiCube(3),[0,2]);
#! Group([ (1,2)(3,5)(4,7)(6,10)(8,11)(9,12), (2,4)(3,6)(5,9)(8,12)(10,11), (1,3)(2,5)(4,8)(7,11)(9,12) ])
#! @EndExampleSession


#! @Arguments M, i
#! @Returns IsPermGroup
#! @Description Returns a permutation group, representing the action of
#! AutomorphismGroup(<A>M</A>) on the <A>i</A>-faces of <A>M</A>.
#! If the automorphism group has a standard set of generators in a standard order, then the output
#! is generated by the action of those generators.
DeclareOperation("AutomorphismGroupOnIFaces", [IsManiplex, IsInt]);
#! @BeginExampleSession
#! gap> AutomorphismGroupOnIFaces(HemiCube(3),2);
#! Group([ (), (2,3), (1,2) ])
#! @EndExampleSession

#! @Arguments M
#! @Returns IsPermGroup
#! @Description Returns a permutation group, representing the action of
#! AutomorphismGroup(<A>M</A>) on the vertices of <A>M</A>.
#! If the automorphism group has a standard set of generators in a standard order, then the output
#! is generated by the action of those generators.
DeclareAttribute("AutomorphismGroupOnVertices", IsManiplex);
#! @BeginExampleSession
#! gap> AutomorphismGroupOnVertices(HemiCube(4));
#! Group([ (1,2)(3,4)(5,6)(7,8), (2,3)(6,8), (3,5)(4,6), (5,7)(6,8) ])
#! @EndExampleSession

#! @Arguments M
#! @Returns IsPermGroup
#! @Description Returns a permutation group, representing the action of
#! AutomorphismGroup(<A>M</A>) on the edges of <A>M</A>.
#! If the automorphism group has a standard set of generators in a standard order, then the output
#! is generated by the action of those generators.
DeclareAttribute("AutomorphismGroupOnEdges", IsManiplex);
#! @BeginExampleSession
#! gap> AutomorphismGroupOnEdges(Simplex(4));
#! Group([ (2,5)(3,6)(4,7), (1,2)(6,8)(7,9), (2,3)(5,6)(9,10), (3,4)(6,7)(8,9) ])
#! @EndExampleSession

#! @Arguments M
#! @Returns IsPermGroup
#! @Description Returns a permutation group, representing the action of
#! AutomorphismGroup(<A>M</A>) on the facets of <A>M</A>.
#! If the automorphism group has a standard set of generators in a standard order, then the output
#! is generated by the action of those generators.
DeclareAttribute("AutomorphismGroupOnFacets", IsManiplex);
#! @BeginExampleSession
#! gap> AutomorphismGroupOnFacets(HemiCube(5));
#! Group([ (), (4,5), (3,4), (2,3), (1,2) ])
#! @EndExampleSession

#! @Chapter Maniplex Properties
#! @Section Number of orbits and transitivity

#! @Arguments M, I
#! @Returns IsInt
#! @Description Returns the number of orbits of chains of type <A>I</A> under
#! the action of AutomorphismGroup(<A>M</A>).
DeclareOperation("NumberOfChainOrbits", [IsManiplex, IsCollection]);
#! @BeginExampleSession
#! gap> NumberOfChainOrbits(Cuboctahedron(),[0,2]);
#! 2
#! @EndExampleSession



#! @Arguments M, i
#! @Returns IsInt
#! @Description Returns the number of orbits of <A>i</A>-faces under
#! the action of AutomorphismGroup(<A>M</A>).
DeclareOperation("NumberOfIFaceOrbits", [IsManiplex, IsInt]);
#! @BeginExampleSession
#! gap> NumberOfIFaceOrbits(SnubDodecahedron(),2);
#! 3
#! @EndExampleSession


#! @Arguments M
#! @Returns IsInt
#! @Description Returns the number of orbits of vertices under
#! the action of AutomorphismGroup(<A>M</A>).
DeclareAttribute("NumberOfVertexOrbits", IsManiplex);
#! @BeginExampleSession
#! gap> NumberOfVertexOrbits(Dual(SnubDodecahedron()));
#! 3
#! @EndExampleSession


#! @Arguments M
#! @Returns IsInt
#! @Description Returns the number of orbits of edges under
#! the action of AutomorphismGroup(<A>M</A>).
DeclareAttribute("NumberOfEdgeOrbits", IsManiplex);
#! @BeginExampleSession
#! gap> NumberOfEdgeOrbits(SnubDodecahedron());
#! 3
#! @EndExampleSession


#! @Arguments M
#! @Returns IsInt
#! @Description Returns the number of orbits of facets under
#! the action of AutomorphismGroup(<A>M</A>).
DeclareAttribute("NumberOfFacetOrbits", IsManiplex);
#! @BeginExampleSession
#! gap> NumberOfFacetOrbits(SnubCube());
#! 3
#! @EndExampleSession
	
#! @Arguments M, I
#! @Returns IsBool
#! @Description Determines whether the action of AutomorphismGroup(<A>M</A>) on
#! chains of type <A>I</A> is transitive.
DeclareOperation("IsChainTransitive", [IsManiplex, IsCollection]);
#! @BeginExampleSession
#! gap> IsChainTransitive(SmallRhombicuboctahedron(),[0,2]);
#! false
#! gap> IsChainTransitive(SmallRhombicuboctahedron(),[0,1]);
#! false
#! gap> IsChainTransitive(Cuboctahedron(),[0,1]);
#! true
#! @EndExampleSession



#! @Arguments M, i
#! @Returns IsBool
#! @Description Determines whether the action of AutomorphismGroup(<A>M</A>) on
#! <A>i</A>-faces is transitive.
DeclareOperation("IsIFaceTransitive", [IsManiplex, IsInt]);
#! @BeginExampleSession
#! gap> IsIFaceTransitive(Cuboctahedron(),1);
#! true
#! @EndExampleSession

#! @Arguments M
#! @Returns IsBool
#! @Description Determines whether the action of AutomorphismGroup(<A>M</A>) on
#! vertices is transitive.
DeclareProperty("IsVertexTransitive", IsManiplex);
#! @BeginExampleSession
#! gap> IsVertexTransitive(Bk2l(4,5));
#! true
#! @EndExampleSession

#! @Arguments M
#! @Returns IsBool
#! @Description Determines whether the action of AutomorphismGroup(<A>M</A>) on
#! edges is transitive.
DeclareProperty("IsEdgeTransitive", IsManiplex);
#! @BeginExampleSession
#! gap> IsEdgeTransitive(Prism(Simplex(3)));
#! false
#! @EndExampleSession

#! @Arguments M
#! @Returns IsBool
#! @Description Determines whether the action of AutomorphismGroup(<A>M</A>) on
#! facets is transitive.
DeclareProperty("IsFacetTransitive", IsManiplex);
#! @BeginExampleSession
#! gap> IsFacetTransitive(Prism(HemiCube(3)));
#! false
#! @EndExampleSession

   
#! @Arguments M
#! @Returns IsBool
#! @Description Determines whether the action of AutomorphismGroup(<A>M</A>) on
#! i-faces is transitive for every i.
DeclareProperty("IsFullyTransitive", IsManiplex);
#! @BeginExampleSession
#! gap> IsFullyTransitive(SmallRhombicuboctahedron());
#! false
#! gap> IsFullyTransitive(Bk2l(4,5));
#! true
#! @EndExampleSession



#! @Section Faithfulness

#! @Arguments M
#! @Description Returns whether the reflexible maniplex <A>M</A> is
#! vertex-faithful; i.e., whether the action of the automorphism
#! group on the vertices is faithful.
DeclareProperty("IsVertexFaithful", IsManiplex);
#! @BeginExampleSession
#! gap> IsVertexFaithful(HemiCube(3));
#! true
#! @EndExampleSession

#! @Arguments M
#! @Description Returns whether the reflexible maniplex <A>M</A> is
#! facet-faithful; i.e., whether the action of the automorphism
#! group on the facets is faithful.
DeclareProperty("IsFacetFaithful", IsManiplex);
#! @BeginExampleSession
#! gap> IsFacetFaithful(HemiCube(3));
#! false
#! gap> IsFacetFaithful(Cube(3));
#! true
#! @EndExampleSession

#! @Arguments M
#! @Returns Q
#! @Description Returns the maximal vertex-faithful reflexible maniplex covered by <A>M</A>.
#! Currently assumes that the number of vertices is finite.
DeclareOperation("MaxVertexFaithfulQuotient", [IsReflexibleManiplex]);
#! @BeginExampleSession
#! gap> SchlafliSymbol(MaxVertexFaithfulQuotient(HemiCrossPolytope(3)));
#! [ 3, 2 ]
#! @EndExampleSession

#! @Arguments M
#! @Returns Q
#! @Description Returns the maximal facet-faithful reflexible maniplex covered by <A>M</A>.
#! Currently assumes that the number of facets is finite.
DeclareOperation("MaxFacetFaithfulQuotient", [IsReflexibleManiplex]);
#! @BeginExampleSession
#! gap> SchlafliSymbol(MaxFacetFaithfulQuotient(HemiCube(3)));
#! [ 2, 3 ]
#! @EndExampleSession



#! @Arguments M, i
#! @Description Returns the subgroup of the automorphism group of <A>M</A> that fixes the base i-face.
#! Currently only implemented for reflexible maniplexes.
DeclareOperation("IFaceStabilizer", [IsManiplex, IsInt]);
#! @BeginExampleSession
#! gap> IFaceStabilizer(Cube(4), 1)
#! Group([ r0, r2, r3 ])
#! gap> Size(last)
#! 12
#! gap> M := ReflexibleManiplex(IFaceStabilizer(Cube(4), 0));
#! reflexible 3-maniplex
#! gap> M = Simplex(3);
#! true
#! @EndExampleSession

#! @Arguments M
#! @Description Returns the subgroup of the automorphism group of <A>M</A> that fixes the base vertex.
#! Currently only implemented for reflexible maniplexes.
DeclareOperation("VertexStabilizer", [IsManiplex]);

#! @Arguments M
#! @Description Returns the subgroup of the automorphism group of <A>M</A> that fixes the base edge.
#! Currently only implemented for reflexible maniplexes.
DeclareOperation("EdgeStabilizer", [IsManiplex]);

#! @Arguments M
#! @Description Returns the subgroup of the automorphism group of <A>M</A> that fixes the base facet.
#! Currently only implemented for reflexible maniplexes.
DeclareOperation("FacetStabilizer", [IsManiplex]);

#! @Arguments M, I
#! @Description Returns the subgroup of the automorphism group of <A>M</A> that fixes the base chain
#! of the type given by <A>L</A>. Currently only implemented for reflexible maniplexes.
DeclareOperation("ChainStabilizer", [IsManiplex, IsCollection]);
#! @BeginExampleSession
#! gap> stab := ChainStabilizer(Cube(4), [0,3]);; Size(stab);
#! 6
#! gap> M := ReflexibleManiplex(stab);; M = Pgon(3);
#! true
#! @EndExampleSession

#! @Arguments M
#! @Description Returns the subgroup of the automorphism group of <A>M</A> that fixes the entire base chain.
#! Currently only implemented for reflexible maniplexes.
DeclareOperation("MaxChainStabilizer", [IsManiplex]);
#! @BeginExampleSession
#! gap> Size(MaxChainStabilizer(Cube(4)));
#! 1
#! gap> M := ReflexibleManiplex([6,3], "(r0 r1)^3 = r0 r2");;
#! gap> Size(MaxChainStabilizer(M));
#! 2
#! @EndExampleSession
