#! @Chapter Comparing maniplexes
#! @Section Quotients and covers

DeclareGlobalFunction("CouldBeQuotient");

#! @Arguments M1, M2
#! Returns whether <A>M1</A> is a quotient of <A>M2</A>.
DeclareOperation("IsQuotient", [IsManiplex, IsManiplex]);

#! @Arguments M1, M2
#! Returns whether <A>M1</A> is a cover of <A>M2</A>.
DeclareOperation("IsCover", [IsManiplex, IsManiplex]);

#! @Arguments M1, M2
#! Returns whether <A>M1</A> is isomorphic to <A>M2</A>.
DeclareOperation("IsIsomorphicManiplex", [IsManiplex, IsManiplex]);

#! @Arguments M
#! Returns the smallest regular cover of <A>M</A>, which is the
#! maniplex whose automorphism group is the connection group
#! of <A>M</A>.
DeclareAttribute("SmallestRegularCover", IsManiplex);

#! @Arguments M, relStr
#! Given a reflexible maniplex <A>M</A>, generates the subgroup S of
#! AutomorphismGroup(<A>M</A>) given by relStr, and returns the quotient
#! maniplex M / S.
#! For example, QuotientManiplex(CubicTiling(2), "(r0 r1 r2 r1)^5, (r1 r0 r1 r2)^2")
#! returns the toroidal map {4,4}_{(5,0),(0,2)}.
#! You can also input this as CubicTiling(2) / "(r0 r1 r2 r1)^5, (r1 r0 r1 r2)^2".
DeclareOperation("QuotientManiplex", [IsReflexibleManiplex, IsString]);

#! @Arguments M, rels
#! Given a reflexible maniplex <A>M</A>, generates the normal closure N of
#! the subgroup S of AutomorphismGroup(<A>M</A>) given by relStr, and returns 
#! the quotient maniplex M / N, which will be reflexible.
#! For example, QuotientManiplex(CubicTiling(2), "(r0 r1 r2 r1)^5, (r1 r0 r1 r2)^2")
#! returns the toroidal map {4,4}_{(1,0)}, because the normal closure of the group
#! generated by (r0 r1 r2 r1)^5 and (r1 r0 r1 r2)^2 is the group generated by r0 r1 r2 r1
#! and r1 r0 r1 r2.
DeclareOperation("ReflexibleQuotientManiplex", [IsManiplex, IsList]);

